import type { Property } from './types'

// Агенты: lm-1 = текущий менеджер (MOCK_USERS id), agent-2 и agent-3 — коллеги
const AGENTS = {
  me:     { agentId: 'lm-1',    agentName: 'Лариса Морозова' },
  anna:   { agentId: 'agent-2', agentName: 'Анна Смирнова' },
  dmitry: { agentId: 'agent-3', agentName: 'Дмитрий Волков' },
}

// Даты относительно 2026-03-14 (сегодня):
// up_to_date      → обновлено < 10 дней назад  → 2026-03-05 и новее
// needs_attention → 10–14 дней назад           → 2026-02-28 … 2026-03-04
// needs_update    → > 14 дней назад            → до 2026-02-27

export const mockProperties: Property[] = [
  // ── МОИ объекты (lm-1) ──────────────────────────────────────────────────
  {
    id: '1',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-03-12', // актуально (2 дня назад)
    status: 'for_sale',
    ...AGENTS.me,
  },
  {
    id: '2',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 2, totalFloors: 10, rooms: 2, area: 120,
    price: 155000, pricePerM2: 2100,
    listedAt: '2025-11-23',
    updatedAt: '2026-03-01', // требует внимания (13 дней)
    status: 'booked',
    ...AGENTS.me,
  },
  {
    id: '3',
    title: 'Загородный дом в современном поселке',
    type: 'Дом',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-03-08', // актуально (6 дней)
    status: 'for_sale',
    ...AGENTS.me,
  },
  {
    id: '4',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-02-10', // нужно обновить (32 дня)
    status: 'sold',
    ...AGENTS.me,
  },
  {
    id: '5',
    title: '2-к квартира посуточно',
    type: 'Квартира',
    category: 'rent',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Пушкина, 3',
    floor: 3, totalFloors: 9, rooms: 2, area: 65,
    price: 1200, pricePerM2: 18,
    listedAt: '2025-11-01',
    updatedAt: '2026-03-10', // актуально (4 дня)
    status: 'for_sale',
    ...AGENTS.me,
  },
  {
    id: '6',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-02-20', // нужно обновить (22 дня)
    status: 'draft',
    ...AGENTS.me,
  },
  {
    id: '10',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-01-15',
    status: 'archive',
    ...AGENTS.me,
  },

  // ── Анна Смирнова ────────────────────────────────────────────────────────
  {
    id: '7',
    title: 'Загородный дом в современном поселке',
    type: 'Дом',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-03-06', // актуально (8 дней)
    status: 'booked',
    ...AGENTS.anna,
  },
  {
    id: '8',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-02-15', // нужно обновить (27 дней)
    status: 'for_sale',
    ...AGENTS.anna,
  },
  {
    id: '9',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-03-03', // требует внимания (11 дней)
    status: 'for_sale',
    ...AGENTS.anna,
  },
  {
    id: '13',
    title: 'Коммерческое помещение на проспекте',
    type: 'Коммерция',
    category: 'commercial',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'пр. Агмашенебели, 44',
    floor: 1, totalFloors: 5, rooms: 1, area: 180,
    price: 320000, pricePerM2: 1778,
    listedAt: '2025-10-15',
    updatedAt: '2026-03-11', // актуально (3 дня)
    status: 'for_sale',
    ...AGENTS.anna,
  },
  {
    id: '11',
    title: '3-к квартира в ЖК Queen\'s Residence',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'ул. Шерифа Химшиашвили, 56а',
    floor: 4, totalFloors: 7, rooms: 1, area: 100,
    price: 200095, pricePerM2: 1245,
    listedAt: '2025-11-23',
    updatedAt: '2026-01-20',
    status: 'archive',
    ...AGENTS.anna,
  },

  // ── Дмитрий Волков ───────────────────────────────────────────────────────
  {
    id: '12',
    title: 'Апартаменты в центре Батуми',
    type: 'Апартаменты',
    category: 'secondary',
    country: 'Грузия',
    city: 'Батуми',
    street: 'пр. Руставели, 12',
    floor: 8, totalFloors: 15, rooms: 2, area: 75,
    price: 98000, pricePerM2: 1307,
    listedAt: '2025-11-23',
    updatedAt: '2026-02-05',
    status: 'archive',
    ...AGENTS.dmitry,
  },
  {
    id: '14',
    title: 'Участок под застройку',
    type: 'Участок',
    category: 'other',
    country: 'Грузия',
    city: 'Кобулети',
    street: 'ул. Гурийская, 7',
    floor: 1, totalFloors: 1, rooms: 0, area: 500,
    price: 75000, pricePerM2: 150,
    listedAt: '2025-09-01',
    updatedAt: '2026-03-02', // требует внимания (12 дней)
    status: 'booked',
    ...AGENTS.dmitry,
  },
  {
    id: '15',
    title: '1-к квартира у моря',
    type: 'Квартира',
    category: 'secondary',
    country: 'Грузия',
    city: 'Батуми',
    street: 'ул. Горгиладзе, 4',
    floor: 5, totalFloors: 12, rooms: 1, area: 45,
    price: 65000, pricePerM2: 1444,
    listedAt: '2025-10-20',
    updatedAt: '2026-03-14', // актуально (сегодня)
    status: 'for_sale',
    ...AGENTS.dmitry,
  },
  {
    id: '16',
    title: 'Офис в бизнес-центре',
    type: 'Коммерция',
    category: 'commercial',
    country: 'Грузия',
    city: 'Тбилиси',
    street: 'пр. Костава, 14',
    floor: 3, totalFloors: 9, rooms: 1, area: 95,
    price: 180000, pricePerM2: 1895,
    listedAt: '2025-08-15',
    updatedAt: '2026-02-25', // нужно обновить (17 дней)
    status: 'for_sale',
    ...AGENTS.dmitry,
  },
]
